/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guiform;

import javax.swing.JTree;

/**
 *
 * @author Trance
 */
public class Runtimer extends javax.swing.JPanel {

    /**
     * Creates new form Runtimer
     */
    public Runtimer(JTree tree) {
        initComponents();
        ShowClassTree(tree);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ClassTreeWindow = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        PopupClassTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jMenuItem1.setText("jMenuItem1");

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("None");
        PopupClassTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        PopupClassTree.setAutoscrolls(true);
        jScrollPane1.setViewportView(PopupClassTree);

        ClassTreeWindow.addTab("Class List Tree", jScrollPane1);
        jScrollPane1.getAccessibleContext().setAccessibleParent(ClassTreeWindow);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        ClassTreeWindow.addTab("Text output", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClassTreeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClassTreeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void ShowClassTree(JTree tree) {
        PopupClassTree = new JTree();
        PopupClassTree.setModel(tree.getModel());
        PopupClassTree.setVisible(true);
        jScrollPane1.setViewportView(tree);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ClassTreeWindow;
    private javax.swing.JTree PopupClassTree;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
